name: mirage
description: Desktop application connecting SNGGLE with PC
publish_to: 'none'
version: 0.0.4

environment:
  sdk: ">=3.1.5"
  flutter: "^3.13.9"

dependencies:
  flutter:
    sdk: flutter

  # A Flutter plugin to play multiple simultaneously audio files, works for Android, iOS, Linux, macOS, Windows, and web.
  # https://pub.dev/packages/audioplayers
  audioplayers: ^5.2.0

  mrumru:
    git:
      url: git@github.com:snggle/mrumru.git

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4

  # CBOR library for Dart. An RFC8949 compliant encoding/decoding CBOR implementation.
  # https://pub.dev/packages/cbor
  cbor: 6.2.0

  # Dart package containing utility methods for common cryptographic and blockchain-specific operations.
  cryptography_utils:
    git:
      url: https://github.com/snggle/cryptography_utils.git

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: ^7.6.4

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1

  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
