name: mirage
description: Desktop application connecting SNGGLE with PC
publish_to: 'none'
version: 0.0.10

environment:
  sdk: "3.2.6"
  flutter: "3.16.9"

dependencies:
  flutter:
    sdk: flutter

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.1.6

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: 7.6.7

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.4.0

  # Provides runtime support for a Dart implementation of protobufs.
  # https://pub.dev/packages/protobuf
  protobuf: 3.1.0

  # Dart package containing implementation of UR (Uniform Resource) for QR code transfer functionality.
  codec_utils:
    git:
      url: https://github.com/snggle/codec_utils.git
      ref: master

  # Dart package containing utility methods for common cryptographic and blockchain-specific operations.
  cryptography_utils:
    git:
      url: https://github.com/snggle/cryptography_utils.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
  # https://pub.dev/packages/bloc_test
  bloc_test: 9.1.7

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.9

flutter:
  uses-material-design: true
