name: mirage
description: Desktop application connecting SNGGLE with PC
publish_to: 'none'
version: 0.0.2

environment:
  sdk: ">=3.1.5"
  flutter: "^3.13.9"

dependencies:
  flutter:
    sdk: flutter

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: ^7.6.4

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1

  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
