name: mirage
description: Desktop application connecting SNGGLE with PC
publish_to: 'none'
version: 0.0.10

environment:
  sdk: "3.2.6"
  flutter: "3.16.9"

dependencies:
  flutter:
    sdk: flutter

  # Etherum Blockies implementation
  # https://pub.dev/packages/blockies_svg
  blockies_svg: 1.0.2

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.1.6

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  # https://pub.dev/packages/flutter_svg
  flutter_svg: 2.0.10+1

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: 7.6.7

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.4.0

  # Provides runtime support for a Dart implementation of protobufs.
  # https://pub.dev/packages/protobuf
  protobuf: 3.1.0

  # A package that provides a set of animated page indicators with a variety of effects.
  # https://pub.dev/packages/smooth_page_indicator
  smooth_page_indicator: ^1.1.0

  # A library to get Audio Devices on Windows.
  # https://pub.dev/packages/win32audio
  win32audio: 1.4.0

  # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  # https://pub.dev/packages/window_manager
  window_manager: 0.4.3

  # Dart package containing implementation of UR (Uniform Resource) for QR code transfer functionality.
  codec_utils:
    git:
      url: https://github.com/snggle/codec_utils.git
      ref: master

  # Dart package containing utility methods for common cryptographic and blockchain-specific operations.
  cryptography_utils:
    git:
      url: https://github.com/snggle/cryptography_utils.git
      ref: master

  # Data Over Audio
  mrumru:
    git:
      url: git@github.com:snggle/mrumru.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
  # https://pub.dev/packages/bloc_test
  bloc_test: 9.1.7

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/wallet_connect_tutorial_images/0.png
    - assets/wallet_connect_tutorial_images/1.png
    - assets/wallet_connect_tutorial_images/2.png
    - assets/wallet_connect_tutorial_images/3.png
    - assets/wallet_connect_tutorial_images/4.png
    - assets/wallet_connect_tutorial_images/5.png
    - assets/wallet_connect_tutorial_images/6.png
    - assets/wallet_connect_tutorial_images/7.png
    - assets/wallet_connect_tutorial_images/8.png
    - assets/wallet_connect_tutorial_images/9.png
    - assets/wallet_connect_tutorial_images/10.png
    - assets/wallet_connect_tutorial_images/11.png
    - assets/wallet_connect_tutorial_images/12.png
    - assets/wallet_connect_tutorial_images/13.png
    - assets/wallet_connect_tutorial_images/14.png
    - assets/wallet_connect_tutorial_images/15.png
    - assets/hard_reset_tutorial_images/0.png
    - assets/hard_reset_tutorial_images/1.png
    - assets/hard_reset_tutorial_images/2.png
    - assets/hard_reset_tutorial_images/3.png
    - assets/hard_reset_tutorial_images/4.png
    - assets/hard_reset_tutorial_images/5.png
    - assets/hard_reset_tutorial_images/6.png
    - assets/hard_reset_tutorial_images/7.png
    - assets/hard_reset_tutorial_images/8.png
